name: Update Lean Project

on:
  schedule:
    - cron: "0 0 * * 0" # once a week on Sunday
  workflow_dispatch: # allows workflow to be triggered manually

jobs:
  update_lean:
    # this is needed for private repositories
    permissions:
      contents: write
      pull-requests: write
      issues: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Lean project
        uses: leanprover-community/lean-update@main
